version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.16
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@6"
      - restore_cache:
          key:  dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
            paths:
                - ~/.cache/cypress
                - node_modules
            key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run Unit Tests
          command: npm run utest
      - run:
          name: Building
          command: npm run build
      - run:
          name: Run Integration Tests
          command: npm run itest
