version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:15.0.1
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Unit Tests
          command: npm run utest
      - run:
          name: Run Integration Tests
          command: npm run itest
